require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/entertainments", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Entertainment. As you add validations to Entertainment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Entertainment.create! valid_attributes
      get entertainments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      entertainment = Entertainment.create! valid_attributes
      get entertainment_url(entertainment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_entertainment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      entertainment = Entertainment.create! valid_attributes
      get edit_entertainment_url(entertainment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Entertainment" do
        expect {
          post entertainments_url, params: { entertainment: valid_attributes }
        }.to change(Entertainment, :count).by(1)
      end

      it "redirects to the created entertainment" do
        post entertainments_url, params: { entertainment: valid_attributes }
        expect(response).to redirect_to(entertainment_url(Entertainment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Entertainment" do
        expect {
          post entertainments_url, params: { entertainment: invalid_attributes }
        }.to change(Entertainment, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post entertainments_url, params: { entertainment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested entertainment" do
        entertainment = Entertainment.create! valid_attributes
        patch entertainment_url(entertainment), params: { entertainment: new_attributes }
        entertainment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the entertainment" do
        entertainment = Entertainment.create! valid_attributes
        patch entertainment_url(entertainment), params: { entertainment: new_attributes }
        entertainment.reload
        expect(response).to redirect_to(entertainment_url(entertainment))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        entertainment = Entertainment.create! valid_attributes
        patch entertainment_url(entertainment), params: { entertainment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested entertainment" do
      entertainment = Entertainment.create! valid_attributes
      expect {
        delete entertainment_url(entertainment)
      }.to change(Entertainment, :count).by(-1)
    end

    it "redirects to the entertainments list" do
      entertainment = Entertainment.create! valid_attributes
      delete entertainment_url(entertainment)
      expect(response).to redirect_to(entertainments_url)
    end
  end
end
